project_id = "rjcruiwlurqdwooarrpa"

[functions.create-payment]
verify_jwt = false

[functions.create-payment-link]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.emitir-nfse]
verify_jwt = false

[functions.cancelar-nfse]
verify_jwt = false

[functions.sync-nfse]
verify_jwt = false

[functions.validar-certificado-nfse]
verify_jwt = false

[functions.pagarme-webhook]
verify_jwt = false

[functions.parecer-ibs-cbs]
verify_jwt = false

[functions.sync-open-banking]
verify_jwt = false

[functions.consultar-cnpj]
verify_jwt = false
