ALTER TABLE public.assinaturas_mecanico ADD CONSTRAINT assinaturas_mecanico_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.budget_planning_lines ADD CONSTRAINT budget_planning_lines_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.card_audit_logs ADD CONSTRAINT card_audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.card_dashboard_cache ADD CONSTRAINT card_dashboard_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.card_importacoes ADD CONSTRAINT card_importacoes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.card_relatorios_gerados ADD CONSTRAINT card_relatorios_gerados_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.card_report_config ADD CONSTRAINT card_report_config_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.card_simulacoes_salvas ADD CONSTRAINT card_simulacoes_salvas_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.card_split_simulacoes ADD CONSTRAINT card_split_simulacoes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.card_transacoes_brutas ADD CONSTRAINT card_transacoes_brutas_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.categorias ADD CONSTRAINT categorias_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.clientes ADD CONSTRAINT clientes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.configuracoes_cartao ADD CONSTRAINT configuracoes_cartao_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE NO ACTION;
ALTER TABLE public.contabilidade_erp_config ADD CONSTRAINT contabilidade_erp_config_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.contabilidade_lancamentos_importados ADD CONSTRAINT contabilidade_lancamentos_importados_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.contabilidade_mapeamento_contas ADD CONSTRAINT contabilidade_mapeamento_contas_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.contabilidade_sincronizacao ADD CONSTRAINT contabilidade_sincronizacao_iniciado_por_fkey FOREIGN KEY (iniciado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.contabilidade_sincronizacao ADD CONSTRAINT contabilidade_sincronizacao_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.contas_pagar ADD CONSTRAINT contas_pagar_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.contas_receber ADD CONSTRAINT contas_receber_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.empresas_mecanico ADD CONSTRAINT empresas_mecanico_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.fornecedores ADD CONSTRAINT fornecedores_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.lancamentos_caixa ADD CONSTRAINT lancamentos_caixa_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.mapeamento_contabil ADD CONSTRAINT mapeamento_contabil_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.nfse_cron_logs ADD CONSTRAINT nfse_cron_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.nfse_rascunhos ADD CONSTRAINT nfse_rascunhos_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.nfse_sync_logs ADD CONSTRAINT nfse_sync_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.notas_fiscais_servico ADD CONSTRAINT notas_fiscais_servico_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.obd2_leituras_mecanico ADD CONSTRAINT obd2_leituras_mecanico_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.open_banking_extratos ADD CONSTRAINT open_banking_extratos_importado_por_fkey FOREIGN KEY (importado_por) REFERENCES auth.users(id) ON DELETE NO ACTION;
ALTER TABLE public.open_banking_extratos ADD CONSTRAINT open_banking_extratos_conciliado_por_fkey FOREIGN KEY (conciliado_por) REFERENCES auth.users(id) ON DELETE NO ACTION;
ALTER TABLE public.open_banking_extratos ADD CONSTRAINT open_banking_extratos_ignorado_por_fkey FOREIGN KEY (ignorado_por) REFERENCES auth.users(id) ON DELETE NO ACTION;
ALTER TABLE public.open_banking_integracoes ADD CONSTRAINT open_banking_integracoes_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES auth.users(id) ON DELETE NO ACTION;
ALTER TABLE public.open_banking_integracoes ADD CONSTRAINT open_banking_integracoes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.open_banking_logs ADD CONSTRAINT open_banking_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.plano_contas ADD CONSTRAINT plano_contas_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.rate_limit_uploads ADD CONSTRAINT rate_limit_uploads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE NO ACTION;
ALTER TABLE public.regua_cobranca_automacao ADD CONSTRAINT regua_cobranca_automacao_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.students ADD CONSTRAINT students_guardian_id_fkey FOREIGN KEY (guardian_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.transacoes_cartao ADD CONSTRAINT transacoes_cartao_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE NO ACTION;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.usuario_empresas ADD CONSTRAINT usuario_empresas_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.usuarios ADD CONSTRAINT usuarios_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.vehicles ADD CONSTRAINT vehicles_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES auth.users(id) ON DELETE SET NULL;
