name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # ou master, dependendo do seu repo

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.9nineteste.9ninebusinesscontrol.com.br
          username: u358595036.amorimadriano83
          password: Enzo@159753
          protocol: ftps
          port: 21
          security: loose
          server-dir: public_html/
